### ISSUE TITLE
3.1.0 peer dependencies

### ISSUE THREAD

**Issue by sgentile** [kreuzerk/primeNG-advanced-growl#164]
Is Angular 5 and primeng 5 really needed for this new feature ?

We'd like to use it - but now we have umet dependencies on this new version

**Comment by kreuzerk** [comment]
Hi @sgentile.

Thanks for mentioning this issue. I could easily fix the unmet peer dependency error but there are other problems. Being Angular 4.x compatible changes the way we package the library. Since version 3.x we only builded our library to be Angular 5 compatible. I have tried to use 3.1.0 inside an Angular 4 app and it does not compile. On the other side when I change the library to be Angular 4 compatible it does not compile with Angular 5 apps. Either way it seems that I can not support both version at the same time.

I will need to investigate this issue further to find a good solution. In the meantime I can package a specific version that has all the new feature and that is angular 4 compatible. You would then need to install this version via _npm install primeng-advanced-growl@angular4_ or something like this. 

Which verison of primeng-advanced-growl are you currently using and did you manage to start your angular 4.x app with version 3.1.0 without compile errors?

**Comment by sgentile** [comment]
Thanks for your explanation.  We are using the library now in 4.3, it works
I just get the unmet dependencies warnings.  I'm under impression it would
build if the peerDependencies was set at  >4 ?

**Comment by kreuzerk** [comment]
@sgentile Sorry for responding that late. Yes, absolutely correct. I just wanted to make sure that this is all I need to change. I have now published a version 3.1.3. When you install this version your unmet peer dependency warnings should disappear. 

Please let me know if it worked.

**Comment by kreuzerk** [comment]
@sgentile I am closing this issue. Please let me know if there are still issues.

Happy new year ;)
