### ISSUE TITLE
get Messge instance for ability of operation

### ISSUE THREAD

**Issue by C-ra-ZY** [kreuzerk/primeNG-advanced-growl#201]
api for now:
createSuccessMessage(messageContent: string, summary: string, additionalProperties?: any): void;

api for future in my mind:
createSuccessMessage(messageContent: string, summary: string, additionalProperties?: any): MessgaeInstance;
so we can add/change message to existing messge box or modify style of existing message box

**Comment by nivekcode** [comment]
Hi @C-ra-ZY. I know its been a while since you brought up this issue. I have just released version 4.1.3. In this version you will receive the message instance when you create a message. Notice that createSuccessMessage will return you an AdvPrimeMessage who has the following interface:

```
export interface AdvPrimeMessage {
    id: string;
    severity: string;
    summary: string;
    detail: string;
    lifeTime?: number;
    additionalProperties?: any;
}
```

With this change you are now able to manipulate the message at a later point. Notice that this is just on of the objects we pass to primeng and not the actual DOM element. 
```
<p-growl #growlMessage
         [(value)]="messages"
         [style]="style"
         [styleClass]="styleClass"
         sticky="sticky"
         (onClick)="messageClicked($event)"
         (onClose)="messageClosed($event)"
         (onHover)="messageEntered($event)">
</p-growl>
```
Therefore I think that you can not change the styles at a later point. Please let me know if version 4.1.3 works for you. Looking forward to your feedback.
